# -*- coding: utf-8 -*-
"""week-15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMMsyCdZu5H6l-MJFK8mWy2qYE-ELNhz

**OBJECTIVE 1: DATA COLLECTION**

**CELL 1: MOUNT GOOGLE DRIVE**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**CELL 2: IMPORT REQUIRED LIBRARIES**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import warnings
warnings.filterwarnings('ignore')

"""**CELL 3: LOAD DATASET**"""

path = "/content/drive/MyDrive/Colab Notebooks/student_performance_dataset.csv"
df = pd.read_csv(path)
print("DATASET LOADED SUCCESSFULLY")

"""**CELL 4: DISPLAY DATASET**"""

df.head()

"""**CELL 5: DATASET INFORMATION**"""

df.info()

"""**CELL 6: DATASET SHAPE**"""

print("NUMBER OF ROWS :", df.shape[0])
print("NUMBER OF COLUMNS :", df.shape[1])

"""**OBJECTIVE 2: DATA CLEANING & PREPROCESSING**

**CELL 7: CHECK MISSING VALUES**
"""

df.isnull().sum()

"""**CELL 8: REMOVE DUPLICATES**"""

print("BEFORE REMOVING DUPLICATES :", df.shape)
df = df.drop_duplicates()
print("AFTER REMOVING DUPLICATES :", df.shape)

"""**CELL 9: CHECK DATA TYPES**"""

df.dtypes

"""**CELL 10: ENCODE CATEGORICAL VARIABLES***"""

le = LabelEncoder()

categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

print("CATEGORICAL VARIABLES ENCODED SUCCESSFULLY")

"""**CELL 11: REMOVE STUDENT_ID**"""

if 'Student_ID' in df.columns:
    df.drop('Student_ID', axis=1, inplace=True)
print("STUDENT_ID COLUMN REMOVED")

"""**CELL 12: DISPLAY CLEANED DATASET**"""

df.head()

"""**OBJECTIVE 3: DESCRIPTIVE STATISTICS**

**CELL 13: STATISTICAL SUMMARY**
"""

df.describe()

"""**CELL 14: AVERAGE STUDY HOURS**"""

avg_study = df['Study_Hours_per_Week'].mean()

print("AVERAGE STUDY HOURS :", round(avg_study, 2))

"""**CELL 15: AVERAGE ATTENDANCE RATE**"""

avg_attendance = df['Attendance_Rate'].mean()

print("AVERAGE ATTENDANCE RATE :", round(avg_attendance, 2))

"""**CELL 16: AVERAGE PAST EXAM SCORES**"""

avg_past = df['Past_Exam_Scores'].mean()

print("AVERAGE PAST EXAM SCORE :", round(avg_past, 2))

"""**CELL 17: AVERAGE FINAL EXAM SCORE**"""

avg_final = df['Final_Exam_Score'].mean()

print("AVERAGE FINAL EXAM SCORE :", round(avg_final, 2))

"""CELL 18: PASS VS FAIL COUNT"""

df['Pass_Fail'].value_counts()

"""**CELL 19: PASS VS FAIL ANALYSIS**"""

df.groupby('Pass_Fail').mean()

"""**CELL 20: INTERNET ACCESS IMPACT**"""

df.groupby('Internet_Access_at_Home')['Final_Exam_Score'].mean()

df.groupby('Extracurricular_Activities')['Final_Exam_Score'].mean()

"""**OBJECTIVE 5: GROUP-BASED ANALYSIS**"""

# STUDY HOURS VS PASS/FAIL

study_analysis = df.groupby('Pass_Fail')['Study_Hours_per_Week'].mean()

study_analysis

# ATTENDANCE VS PASS/FAIL

attendance_analysis = df.groupby('Pass_Fail')['Attendance_Rate'].mean()

attendance_analysis

# GENDER VS PASS RATE

gender_analysis = df.groupby('Gender')['Pass_Fail'].mean()

gender_analysis

# PARENTAL EDUCATION ANALYSIS

parent_analysis = df.groupby('Parental_Education_Level')['Final_Exam_Score'].mean()

parent_analysis

"""**OBJECTIVE 6: RELATIONSHIP ANALYSIS**"""

# CORRELATION MATRIX

corr = df.corr()

corr

# STUDY HOURS VS FINAL EXAM SCORE

plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df['Study_Hours_per_Week'],
    y=df['Final_Exam_Score']
)

plt.title("STUDY HOURS VS FINAL EXAM SCORE")

plt.show()

# ATTENDANCE VS FINAL EXAM SCORE

plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df['Attendance_Rate'],
    y=df['Final_Exam_Score']
)

plt.title("ATTENDANCE VS FINAL EXAM SCORE")

plt.show()

# PASS VS FAIL DISTRIBUTION

fig = px.bar(
    df['Pass_Fail'].value_counts(),
    title='PASS VS FAIL DISTRIBUTION',
    color_discrete_sequence=['blue']
)

fig.show()

# GENDER DISTRIBUTION

fig = px.pie(
    df,
    names='Gender',
    title='GENDER DISTRIBUTION',
    color_discrete_sequence=px.colors.sequential.Blues
)

fig.show()

# STUDY HOURS DISTRIBUTION

fig = px.histogram(
    df,
    x='Study_Hours_per_Week',
    title='STUDY HOURS DISTRIBUTION',
    color_discrete_sequence=['blue']
)

fig.show()

# ATTENDANCE RATE DISTRIBUTION

fig = px.histogram(
    df,
    x='Attendance_Rate',
    title='ATTENDANCE RATE DISTRIBUTION',
    color_discrete_sequence=['blue']
)

fig.show()

# FINAL EXAM SCORE DISTRIBUTION

fig = px.histogram(
    df,
    x='Final_Exam_Score',
    title='FINAL EXAM SCORE DISTRIBUTION',
    color_discrete_sequence=['blue']
)

fig.show()

# BOX PLOT FOR FINAL EXAM SCORE

fig = px.box(
    df,
    y='Final_Exam_Score',
    title='BOX PLOT - FINAL EXAM SCORE',
    color_discrete_sequence=['blue']
)

fig.show()

# CORRELATION HEATMAP

fig = px.imshow(
    df.corr(),
    text_auto=True,
    title='CORRELATION HEATMAP',
    color_continuous_scale='RdPu'
)

fig.show()

# CREATE RISK CATEGORIES

conditions = [

    (
        (df['Attendance_Rate'] < 60) &
        (df['Study_Hours_per_Week'] < 10) &
        (df['Past_Exam_Scores'] < 50)
    ),

    (
        (df['Attendance_Rate'] >= 60) &
        (df['Attendance_Rate'] < 80)
    ),

    (
        (df['Attendance_Rate'] >= 80)
    )
]

risk_labels = ['HIGH RISK', 'MEDIUM RISK', 'LOW RISK']

df['Risk_Level'] = np.select(conditions, risk_labels, default='NORMAL RISK')

df[['Risk_Level']].head()

# RISK LEVEL DISTRIBUTION

fig = px.pie(
    df,
    names='Risk_Level',
    title='RISK LEVEL DISTRIBUTION',
    color_discrete_sequence=px.colors.sequential.RdPu
)

fig.show()

"""OBJECTIVE 9: PREDICTIVE MODELING (LOGISTIC REGRESSION)"""

# DEFINE FEATURES AND TARGET

X = df.drop(['Pass_Fail', 'Risk_Level'], axis=1)

y = df['Pass_Fail']

# FEATURE SCALING

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# TRAIN TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print("TRAINING DATA SHAPE :", X_train.shape)
print("TESTING DATA SHAPE :", X_test.shape)

# TRAIN LOGISTIC REGRESSION MODEL

model = LogisticRegression()

model.fit(X_train, y_train)

print("MODEL TRAINING COMPLETED")

# PREDICTIONS

y_pred = model.predict(X_test)

y_prob = model.predict_proba(X_test)[:,1]

print(y_pred[:10])

"""OBJECTIVE 10: MODEL EVALUATION"""

# ACCURACY SCORE

accuracy = accuracy_score(y_test, y_pred)

print("ACCURACY :", round(accuracy*100,2), "%")

# PRECISION SCORE

precision = precision_score(y_test, y_pred)

print("PRECISION :", round(precision,2))

# RECALL SCORE

recall = recall_score(y_test, y_pred)

print("RECALL :", round(recall,2))

# F1 SCORE

f1 = f1_score(y_test, y_pred)

print("F1 SCORE :", round(f1,2))

# CONFUSION MATRIX

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='RdPu'
)

plt.title("CONFUSION MATRIX")
plt.xlabel("PREDICTED")
plt.ylabel("ACTUAL")

plt.show()

# CLASSIFICATION REPORT

print(classification_report(y_test, y_pred))

# ROC-AUC SCORE

roc_auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC SCORE :", round(roc_auc,2))

# ROC CURVE

fpr, tpr, threshold = roc_curve(y_test, y_prob)

plt.figure(figsize=(8,5))

plt.plot(fpr, tpr)

plt.title("ROC CURVE")
plt.xlabel("FALSE POSITIVE RATE")
plt.ylabel("TRUE POSITIVE RATE")

plt.show()

# ==========================================================
# STUDENT RISK DASHBOARD
# ==========================================================

fig = px.bar(
    df,
    x='Risk_Level',
    color='Pass_Fail',
    title='STUDENT RISK DASHBOARD',
    color_discrete_sequence=px.colors.sequential.RdPu
)

fig.show()

# ATTENDANCE ANALYSIS DASHBOARD

fig = px.scatter(
    df,
    x='Attendance_Rate',
    y='Final_Exam_Score',
    color='Pass_Fail',
    title='ATTENDANCE ANALYSIS DASHBOARD',
    color_discrete_sequence=px.colors.sequential.Pinkyl
)

fig.show()

# STUDY HOURS DASHBOARD

fig = px.scatter(
    df,
    x='Study_Hours_per_Week',
    y='Final_Exam_Score',
    color='Risk_Level',
    title='STUDY HOURS DASHBOARD',
    color_discrete_sequence=px.colors.sequential.RdPu
)

fig.show()

import pandas as pd
import plotly.express as px

# INTERACTIVE CORRELATION HEATMAP

# Drop the 'Risk_Level' column before calculating correlation as it's a string column
# and can't be converted to a float for correlation calculation.
corr_df = df.drop('Risk_Level', axis=1).corr()

fig = px.imshow(
    corr_df,
    text_auto=True,
    title='INTERACTIVE CORRELATION HEATMAP',
    color_continuous_scale='RdPu'
)

fig.show()